name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to main branch

env:
  TF_DIR: ./Day-2-all-config-file  # Global environment variable

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
